on:
  push:
    branches:
      - production

name: 🚀 Deploy website on push to production

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_SELLFLUENCE }}
          username: ${{ secrets.FTP_USERNAME_SELLFLUENCE  }}
          password: ${{ secrets.FTP_PASSWORD_SELLFLUENCE  }}
          server-dir: /
          exclude: |
            testScripts/**
            node_modules/**
            .gitignore/**
            .github/**